### ISSUE TITLE
Image is pushed with tag "main" when tag is set via an environment variable "IMAGE_TAG"

### ISSUE THREAD

**Issue by darkmattercoder** [actions-hub/docker#3]
I noticed a weird behaviour in the following workflow:

```
name: Deploy to docker hub

on: [push, pull_request, workflow_dispatch]

jobs:
  deploy:
    runs-on: ubuntu-latest
    env: 
      IMAGE_TAG: latest
      DOCKER_USERNAME: darkmattercoder
    steps:
      - uses: actions/checkout@master
      - name: Build image
        if: success()
        run: ci/build-dockerimage.sh ${GITHUB_REPOSITORY} ${IMAGE_TAG} .
      - name: Test image
        if: success()
        run: ci/test-dockerimage.sh ${GITHUB_REPOSITORY} ${IMAGE_TAG} test.md
      - name: Login to docker hub
        if: success()
        uses: actions-hub/docker/login@master
        env:
          DOCKER_PASSWORD: ${{ secrets.DOCKERHUB_PASSWORD }}
      - name: Push to docker registry
        if: success()
        uses: actions-hub/docker@master
        with:
          args: push ${GITHUB_REPOSITORY}:${IMAGE_TAG} 
```

Where the log of the github action tells me, that the image should have been pushed with tag `main` instead the `latest` specified via `$IMAGE_TAG` above. I have no clue where that `main` is suddenly coming from:

```
Run actions-hub/docker@master
  with:
    args: push ${GITHUB_REPOSITORY}:${IMAGE_TAG}
  env:
    IMAGE_TAG: main
    DOCKER_USERNAME: darkmattercoder
    IMAGE_NAME: darkmattercoder/docker-markdown-pdf
/usr/bin/docker run --name b8a8bd8d26462d8802c946fa8b6aaf_5a48ab --label 179394 --workdir /github/workspace --rm -e IMAGE_TAG -e DOCKER_USERNAME -e IMAGE_NAME -e INPUT_ARGS -e INPUT_NAME -e INPUT_TAG -e INPUT_DOCKER_USERNAME -e INPUT_DOCKER_PASSWORD -e INPUT_DOCKER_REGISTRY_URL -e HOME -e GITHUB_JOB -e GITHUB_REF -e GITHUB_SHA -e GITHUB_REPOSITORY -e GITHUB_REPOSITORY_OWNER -e GITHUB_RUN_ID -e GITHUB_RUN_NUMBER -e GITHUB_RETENTION_DAYS -e GITHUB_ACTOR -e GITHUB_WORKFLOW -e GITHUB_HEAD_REF -e GITHUB_BASE_REF -e GITHUB_EVENT_NAME -e GITHUB_SERVER_URL -e GITHUB_API_URL -e GITHUB_GRAPHQL_URL -e GITHUB_WORKSPACE -e GITHUB_ACTION -e GITHUB_EVENT_PATH -e GITHUB_ACTION_REPOSITORY -e GITHUB_ACTION_REF -e GITHUB_PATH -e GITHUB_ENV -e RUNNER_OS -e RUNNER_TOOL_CACHE -e RUNNER_TEMP -e RUNNER_WORKSPACE -e ACTIONS_RUNTIME_URL -e ACTIONS_RUNTIME_TOKEN -e ACTIONS_CACHE_URL -e GITHUB_ACTIONS=true -e CI=true -v "/var/run/docker.sock":"/var/run/docker.sock" -v "/home/runner/work/_temp/_github_home":"/github/home" -v "/home/runner/work/_temp/_github_workflow":"/github/workflow" -v "/home/runner/work/_temp/_runner_file_commands":"/github/file_commands" -v "/home/runner/work/docker-markdown-pdf/docker-markdown-pdf":"/github/workspace" 179394:57b8a8bd8d26462d8802c946fa8b6aaf push ${GITHUB_REPOSITORY}:${IMAGE_TAG}
The push refers to repository [docker.io/darkmattercoder/docker-markdown-pdf]
tag does not exist: darkmattercoder/docker-markdown-pdf:main
```

Even when I add an additional 

```
env: 
  IMAGE_TAG: latest
```

to the step, the value the action gets called with remains `main`.

I do not even know if the issue is correctly filed against this action or if the strange behaviour is related to some inner mechanics of github actions itself.
